"""Day 25 - HR ticket persistence with SQLite (Python's built-in sqlite3).

No ORM: a single tiny module with explicit SQL, so the data flow stays obvious.
The ticket id is generated by SQLite (autoincrement primary key) - never by the
LLM. Data persists between application restarts because it lives in a file.

    create_ticket(...)  -> inserts a row, returns the full ticket (with real id)
    get_all_tickets()   -> returns every ticket
    init_db()           -> creates the table if needed (safe to call repeatedly)
"""

from __future__ import annotations

import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from app.config import TICKETS_DB_PATH

logger = logging.getLogger("tickets")

VALID_STATUSES = ("open", "closed")
DEFAULT_STATUS = "open"


class TicketError(Exception):
    """Raised for ticket validation / persistence problems."""


def _resolve(db_path: Path | None) -> Path:
    """Fall back to the configured path, read at call time (test-friendly)."""
    return db_path if db_path is not None else TICKETS_DB_PATH


def _connect(db_path: Path | None = None) -> sqlite3.Connection:
    """Open a SQLite connection, creating the parent folder if needed."""
    db_path = _resolve(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    return conn


def init_db(db_path: Path | None = None) -> None:
    """Create the tickets table if it does not already exist (idempotent)."""
    resolved = _resolve(db_path)
    with _connect(resolved) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS tickets (
                ticket_id   INTEGER PRIMARY KEY AUTOINCREMENT,
                employee_id INTEGER NOT NULL,
                topic       TEXT    NOT NULL,
                description TEXT    NOT NULL,
                status      TEXT    NOT NULL,
                created_at  TEXT    NOT NULL
            )
            """
        )
    logger.info("Ticket database ready at %s", resolved)


def _row_to_dict(row: sqlite3.Row) -> dict:
    return {
        "ticket_id": row["ticket_id"],
        "employee_id": row["employee_id"],
        "topic": row["topic"],
        "description": row["description"],
        "status": row["status"],
        "created_at": row["created_at"],
    }


def _find_duplicate(conn: sqlite3.Connection, employee_id: int, topic: str) -> dict | None:
    """Return an existing OPEN ticket with the same employee + normalized topic.

    Deterministic, no embeddings: duplicate protection is an exact match on
    employee id and case-insensitive/trimmed topic among open tickets.
    """
    cur = conn.execute(
        """
        SELECT * FROM tickets
        WHERE employee_id = ?
          AND LOWER(TRIM(topic)) = LOWER(TRIM(?))
          AND status = 'open'
        ORDER BY ticket_id DESC
        LIMIT 1
        """,
        (employee_id, topic),
    )
    row = cur.fetchone()
    return _row_to_dict(row) if row else None


def create_ticket(
    employee_id: int,
    topic: str,
    description: str,
    db_path: Path | None = None,
) -> dict:
    """Insert a ticket and return it (including the SQLite-generated id).

    Duplicate protection: if an OPEN ticket already exists for the same employee
    and normalized topic, that existing ticket is returned with
    ``"duplicate": True`` instead of creating another row.

    Fails: blank topic/description -> TicketError; DB errors -> TicketError.
    """
    if not topic or not topic.strip():
        raise TicketError("topic must not be empty.")
    if not description or not description.strip():
        raise TicketError("description must not be empty.")
    try:
        emp = int(employee_id)
    except (TypeError, ValueError) as exc:
        raise TicketError(f"Invalid employee_id: {employee_id!r}") from exc

    created_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    try:
        with _connect(db_path) as conn:
            init_sql = (
                "CREATE TABLE IF NOT EXISTS tickets ("
                "ticket_id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "employee_id INTEGER NOT NULL, topic TEXT NOT NULL,"
                "description TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)"
            )
            conn.execute(init_sql)  # ensure table exists even on first use

            existing = _find_duplicate(conn, emp, topic)
            if existing:
                logger.info("Duplicate ticket suppressed for employee %s", emp)
                existing["duplicate"] = True
                return existing

            cur = conn.execute(
                "INSERT INTO tickets (employee_id, topic, description, status, created_at) "
                "VALUES (?, ?, ?, ?, ?)",
                (emp, topic.strip(), description.strip(), DEFAULT_STATUS, created_at),
            )
            ticket_id = cur.lastrowid
    except sqlite3.Error as exc:
        logger.error("Ticket insert failed.")
        raise TicketError("Could not save the ticket.") from exc

    logger.info("Ticket created (ticket_id=%s, employee_id=%s)", ticket_id, emp)
    return {
        "ticket_id": ticket_id,
        "employee_id": emp,
        "topic": topic.strip(),
        "description": description.strip(),
        "status": DEFAULT_STATUS,
        "created_at": created_at,
        "duplicate": False,
    }


def get_all_tickets(db_path: Path | None = None) -> list[dict]:
    """Return all tickets (empty list if the table does not exist yet)."""
    try:
        with _connect(db_path) as conn:
            cur = conn.execute("SELECT * FROM tickets ORDER BY ticket_id")
            return [_row_to_dict(r) for r in cur.fetchall()]
    except sqlite3.Error:
        return []
